DROP DATABASE IF EXISTS integracao;
CREATE DATABASE integracao;

USE integracao;

CREATE TABLE USER(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NOME VARCHAR(45) NOT NULL,
    CPF VARCHAR(45) NOT NULL
    );
    
SELECT * FROM USER;